contracts/dapis/DapiServer.sol
We need to be able to read multiple Beacons/Beacon sets and the block number at that time with a single static call, which is why ExtendedMulticall is needed in DapiServer.
=> Have DapiServer inherit ExtendedMulticall

contracts/authorizers/RequesterAuthorizer.sol, contracts/authorizers/interfaces/IAuthorizerV0.sol, contracts/authorizers/interfaces/IRequesterAuthorizer.sol, test/authorizers/RequesterAuthorizerWithAirnode.sol.js, test/authorizers/RequesterAuthorizerWithManager.sol.js
Added a backwards-compatible `isAuthorizedV0()` function to RequesterAuthorizer similar to the ones from @api3/airnode-protocol@0.6.0. I'm planning to do a release after merging this.
=> Carry over backwards-compatible RequesterAuthorizer

contracts/dapis/DapiServer.sol, test/dapis/DapiServer.sol.js
I added a new condition parameter, `deviationReference`, which implicitly was `0` in the previous implementation. How to use it:
- If you want to set up a traditional price data feed and replicate the existing Beacons, set it to 0
- If you want to set up a signed temperature data feed in Celsius with 18 decimals, set it to `-273 * 10^18` and choose a deviation threshold that satisfies your deviation characteristics
- If you want to set up a 18 decimal temperature of ocean data feed that is expected to be between 0 and 100 Celsius degrees, you can still set `deviationReference` to `-100 * 10^18` to prevent it from freaking out when it's near 0
This is nicer than https://github.com/api3dao/airnode-protocol-v1/pull/46 because the user of signed data only needs to know the number of decimals, …
=> Add deviationReference to PSP conditions

contracts/authorizers/RequesterAuthorizer.sol, contracts/authorizers/RequesterAuthorizerWithAirnode.sol, contracts/authorizers/RequesterAuthorizerWithManager.sol, test/authorizers/RequesterAuthorizerWithAirnode.sol.js
Closes https://github.com/api3dao/airnode-protocol-v1/issues/47
The current implementation of RequesterAuthorizers allow endpoint with ID 0 to be whitelisted to support https://github.com/api3dao/airnode/issues/1527 However, during our research, we realized that using the endpoint with ID 0 for this purpose is not appropriate and that should be a proper endpoint with an ID. Then, instead of removing the endpoint-specific authorization functionality, I used authorizations with endpoint ID 0 as a blanket authorization across all endpoints of the Airnode.
Although the current ERC20-based monetization contracts can be updated according to this, I didn't bother because they have gone obsolete https://github.com/api3dao/airnode-protocol-v1/issues/45
=> Blanket authorization

contracts/allocators/Allocator.sol, contracts/allocators/AllocatorWithAirnode.sol, contracts/allocators/AllocatorWithManager.sol, contracts/authorizers/RequesterAuthorizer.sol, contracts/authorizers/RequesterAuthorizerWithAirnode.sol, contracts/authorizers/RequesterAuthorizerWithManager.sol, contracts/utils/ExpiringMetaCallForwarder.sol, contracts/utils/mock/MockExpiringMetaCallForwarderTarget.sol, test/allocators/AllocatorWithAirnode.sol.js, test/allocators/AllocatorWithManager.sol.js, test/authorizers/RequesterAuthorizerWithAirnode.sol.js, test/authorizers/RequesterAuthorizerWithManager.sol.js, test/monetization/RequesterAuthorizerWhitelisterWithTokenDeposit.sol.js, test/monetization/RequesterAuthorizerWhitelisterWithTokenPayment.sol.js, test/utils/ExpiringMetaCallForwarder.sol.js
Closes https://github.com/api3dao/airnode-protocol-v1/issues/38
The main use-case I was thinking about is a user sends a whitelisting request to an Airnode operator on ChainAPI on a random chain. The Airnode operator doesn't have the respective currency, and doesn't want to pay for other people's whitelisting. Then, they create a meta-tx, which ChainAPI sends to the requester to execute. Ideally this should be a whitelisted extension because the Airnode operator cannot undo the whitelisting for the same reasons that they can't execute the initial whitelisting.
Meta-txes typically use nonces to prevent replays. However, considering that there may be multiple parties that request such whitelistings, we can't use nonces. Note that this is because our use-case is fundamentally different from …
=> Use ERC2771 to enable a limited subset of meta-txes for Authorizers and Allocators

contracts/dapis/DapiServer.sol, contracts/dapis/interfaces/IDapiServer.sol, test/dapis/DapiServer.sol.js
Closes https://github.com/api3dao/airnode-protocol-v1/issues/54
I didn't want to weigh down `updateBeaconSetWithSignedData()` so I just duplicated the implementation for domain-signed data. https://github.com/api3dao/airnode-protocol-v1/issues/34 also requires additions to DapiServer so this may cause the contract size limit to be exceeded. That can be addressed later.
=> Domain signed data v2

.github/workflows/test.yml, contracts/dapis/proxies/DapiProxy.sol, contracts/dapis/proxies/DapiProxyWithOev.sol, contracts/dapis/proxies/DataFeedProxy.sol, contracts/dapis/proxies/DataFeedProxyWithOev.sol, contracts/dapis/proxies/ProxyFactory.sol, contracts/dapis/proxies/interfaces/IProxyFactory.sol, test/dapis/proxies/ProxyFactory.sol.js
Closes #58 https://github.com/api3dao/airnode-protocol-v1/issues/65
I started off by implementing what I was talking about earlier, i.e., a factory that can be configured to allow/disallow the deployment of arbitrary contracts. That requires the deployment transaction to provide the entire bytecode in calldata, which costs an additional 20,000 (so 200,000 -> 220,000 gas cost for a DapiProxy deployment, more for the OEV counterparts). I figured that being able to register new proxy contract types isn't worth this overhead, especially since we don't foresee using that feature. So I embedded the four proxy types in the factory contract instead, which results in the cheapest deployment (along with https://github.com/api3dao/airnode-protocol-v1/issues/66).
Note that I also walked back on …
=> Add ProxyFactory

contracts/utils/ExpiringMetaTxForwarder.sol, contracts/utils/interfaces/IExpiringMetaTxForwarder.sol, test/utils/ExpiringMetaTxForwarder.sol.js
I figured it's a good idea to be able to nullify previously issued signatures. The nullification can also be done through meta-txes if the inheriting contract supports it (which AccessControlRegistry does).
=> Add meta-tx nullification

contracts/allocators/Allocator.sol, contracts/allocators/AllocatorWithAirnode.sol, contracts/allocators/AllocatorWithManager.sol, contracts/authorizers/RequesterAuthorizer.sol, contracts/authorizers/RequesterAuthorizerWithAirnode.sol, contracts/authorizers/RequesterAuthorizerWithManager.sol
I investigated https://github.com/api3dao/airnode-protocol-v1/issues/83 again only found this to be an improvement with no drawbacks. The contracts with managers were storing the role description hashes only to be used once in the constructor.
=> Don't store description hashes for contracts with managers

contracts/dapis/DapiServer.sol, contracts/dapis/proxies/DapiProxy.sol, test/dapis/DapiServer.sol.js
Addressing API3-02
- Uses median instead of mean to calculate Beacon set timestamps
- Allows `updateBeaconSetWithBeacons()` even if it doesn't update the Beacon set timestamp, as long as it updates the Beacon set value. This is because updating individual Beacons will not necessarily affect the Beacon set timestamp, but the resulting value will be fresher
- Small `updateBeaconWithSignedData()` refactor
=> Median Beacon set timestamp

contracts/dapis/DapiServer.sol, contracts/dapis/interfaces/IDapiServer.sol
Addresses API3-02
Makes `aggregateBeacons()` private. As a note, the response plan mentioned having `updateBeaconSetWithBeacons()` return the updated Beacon set to replace the `aggregateBeacons()` interface in function. However, this doesn't really work because `updateBeaconSetWithBeacons()` reverts if it can't update the Beacon set. The reader forcing Beacon set updates beforehand is not the intended user flow so I decided against reworking the interface just to enable this. This is still possible in a few ways:
- The reader `tryMulticall()`s a `updateBeaconSetWithBeacons()` and the read call
- The reader calls `updateBeaconSetWithBeacons()` in a try-catch statement
- The reader makes a low-level call to `updateBeaconSetWithBeacons()` and doesn't care if the call fails
=> Remove aggregation interface

contracts/dapis/DapiServer.sol, contracts/protocol/AirnodeRequester.sol, contracts/protocol/mock/MockAirnodeRequester.sol, contracts/protocol/mock/MockSponsor.sol, test/dapis/DapiServer.sol.js
Addresses API3-03
- Since signed data can no longer be used to update Beacon sets without updating the respective Beacon, and updating the respective Beacon is only allowed if doing so increases its timestamp, we no longer need to invalidate old signatures. Omitting this validation is consistent with any old Beacon being usable to update a Beacon set.
- Removes the timestamp validation implementation in AirnodeRequester and tells the user to implement it themselves
- Increases the tolerance for timestamps from the future from 15 minutes to 1 hour. This was previously set at the low value of 15 minutes because using mean for timestamp aggregation enabled some attack scenarios. Now that we are using median for timestamp aggregation, a minority attacker group reporting large timestamps will …
=> Do not invalidate old signatures

contracts/dapis/proxies/DapiProxy.sol, contracts/dapis/proxies/DapiProxyWithOev.sol, contracts/dapis/proxies/DataFeedProxy.sol, contracts/dapis/proxies/DataFeedProxyWithOev.sol
Addresses API3-05
Since we deploy proxies as regular contracts for reduced external call overhead, we want to keep their bytecode small. Therefore, instead of adding checks in them, I added a notice to each of them to warn the user about this issue.
=> Add notices about proxy constructor argument validation

contracts/utils/ExternalMulticall.sol, test/utils/ExternalMulticall.sol.js
Addresses API3-07
Populates the returndata of `tryExternalMulticall()` calls to EOAs in a way consistent with how `externalMulticall()` calls to EOAs revert
=> Populate returndata of tryExternalMulticall() to EOA

contracts/utils/ExternalMulticall.sol, contracts/utils/mock/MockExternalMulticall.sol, test/utils/ExternalMulticall.sol.js
Addresses API3-09
- Added some guidance to ExternalMulticall
- Made ExternalMulticall abstract so that it's a bit more difficult to deploy as it is and use it in a wrong way
=> Make ExternalMulticall abstract and add guidance

contracts/dapis/DapiServer.sol, contracts/dapis/interfaces/IDapiServer.sol, test/dapis/DapiServer.sol.js, test/test-utils.js
Addresses the OEV portion of API3-01
The solution for signed updates in https://github.com/api3dao/airnode-protocol-v1/pull/96 doesn't work well for OEV updates because Beacons specific to OEV proxies are not live Beacons, i.e., the respective Airnode cannot update these on its own despite being censored by the OEV relay. OEV updates are multi-party process, which can be piggybacked on for a nicer solution.
Considering that an absolute majority of Beacon sets would be able to fully control the aggregation, it doesn't degrade the security guarantees to allow them to do the aggregation off-chain and write the aggregated value to the chain (except as seen above, the aggregation requirements are slightly relaxed). This resolves API3-01 by pushing the timestamp-related checks from the chain to …
=> Reworks OEV to aggregate off chain

contracts/utils/ExtendedSelfMulticall.sol, contracts/utils/interfaces/IExtendedSelfMulticall.sol, test/utils/ExtendedSelfMulticall.sol.js
Closes https://github.com/api3dao/airnode-protocol-v1/issues/93
I figured I'd name the function to be less assertive than `isContract()`
=> Adds containsBytecode()

contracts/dapis/DataFeedServer.sol, contracts/dapis/OevDataFeedServer.sol, test/dapis/Api3ServerV1.sol.js, test/dapis/DataFeedServerFull.sol.js
Refer to https://api3workspace.slack.com/archives/C03GPUX7P71/p1678174457169759?thread_ts=1678101311.141659&cid=C03GPUX7P71 for context
Previous implementation:
- Beacon updates require timestamp to be updated
- Beacon set updates require timestamp or value to be updated
- OEV updates require timestamp to be updated
New implementation:
- Beacon updates require timestamp and value to be updated (not updating the value is allowed if the previous timestamp was zero)
- Beacon set updates require timestamp and value to be updated (not updating the value is allowed if the previous timestamp was zero)
- OEV updates require timestamp and value to be updated (not updating the value is allowed if the previous timestamp was zero), and require the value to be different than the value of the base data …
=> Require all updates to update both the timestamp and the value

contracts/dapis/DataFeedServer.sol, contracts/dapis/OevDataFeedServer.sol, test/dapis/Api3ServerV1.sol.js, test/dapis/DataFeedServerFull.sol.js
Based on our call yesterday, reverts the changes to go back to the state at https://github.com/api3dao/airnode-protocol-v1/tree/a36cadbdce4e031f761bb99701e1d5f254dd6316
As such, the only post-audit changes are:
- Added `containsBytecode()` https://github.com/api3dao/airnode-protocol-v1/commit/6d152925cc2ae716103d7360048133d5c67e0ead
- Removed PSP Beacon set updates from Api3ServerV1 https://github.com/api3dao/airnode-protocol-v1/commit/6d38d5ff433726cd7a20ffa118e8a6c809bb4edb
- OwnableCallForwarder constructor gets the owner address as an argument (we already use this version in manager-multisig) https://github.com/api3dao/airnode-protocol-v1/commit/d5d1310297d9e9b9a7f61340c063d042dd05bfaa
=> Revert added update requirements

contracts/dapis/proxies/DapiProxy.sol, contracts/dapis/proxies/DapiProxyWithOev.sol, contracts/dapis/proxies/DataFeedProxy.sol, contracts/dapis/proxies/DataFeedProxyWithOev.sol, contracts/dapis/proxies/ProxyFactory.sol, contracts/dapis/proxies/interfaces/IProxy.sol, contracts/dapis/proxies/interfaces/IProxyFactory.sol, test/dapis/proxies/DapiProxy.sol.js, test/dapis/proxies/DapiProxyWithOev.sol.js, test/dapis/proxies/DataFeedProxy.sol.js, test/dapis/proxies/DataFeedProxyWithOev.sol.js, test/dapis/proxies/ProxyFactory.sol.js
I updated the names on @Ashar2shahid's request. I think the api3ServerV1 name (rather than something more general) makes sense in that if one ever uses a custom data feed server implementation it will most likely not use proxies, so this proxy factory is in practice Api3ServerV1 specific.
=> Rename DapiServer as Api3ServerV1 in proxies and factory

contracts/dapis/proxies/ProxyFactory.sol, contracts/dapis/proxies/interfaces/IProxyFactory.sol, test/dapis/proxies/ProxyFactory.sol.js
I figured I'd add this since https://github.com/api3dao/airnode-protocol-v1/pull/119 will require ProxyFactory to be redeployed anyway.
We will have `@api3/contracts` to export a function that predicts what a proxy address will be without deploying it. This address can also be obtained by performing a static call to one of the deployment functions. However, neither of these methods are available if it's a contract that needs to predict the address of a proxy. Instead, the user will have to implement the proxy address prediction function in their contract, and will likely make a mistake while doing (for example I forgot to hash the dAPI name while implementing this and only realized that when the tests reverted, another mistake I foresee is omitting the validations). So these are …
=> Add proxy address prediction functions
